name: ElysiaCitizens
authors: [hellcatv, lyuma, FifthOracle, hebrewhamm3r]
version: 0.1
main: org.elysia.ElysiaCitizens
depend: [Citizens]
website: https://github.com/pathorn/ElysiaCitizens
description: ElysiaCitizens allows more intelligent mobs
commands:
   spawn:
     description: Spawn a villager
     usage: /spawn <type>
#     permission: elysiacitizens.spawn
#permissions:
#  elysiacitizens.*:
#     description: Give access to all elysiacitizens commands
#     children:
#        elysiacitizens.spawn: true
#  elysiacitizens.spawn:
#     default: true
#     description: Allows you to spawn creatures
